apiVersion: v1
kind: Secret
metadata:
  name: regional-analytics-secrets
  namespace: regional-analytics
type: Opaque
stringData:
  DATABASE_URL: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  EMBEDDINGS_POSTGRES_DSN: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  CLUSTERING_POSTGRES_DSN: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  SUMMARIZATION_POSTGRES_DSN: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  RANKING_POSTGRES_DSN: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  SENTIMENT_POSTGRES_DSN: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  API_DATABASE_URL: postgresql://hack_user:hack_pass@192.168.0.103:5432/hack_db
  VK_TOKEN: replace-me
  API_JWT_ISSUER: https://issuer.example.internal
  API_JWT_AUDIENCE: regional-analytics
  API_JWKS_URL: https://issuer.example.internal/.well-known/jwks.json
  SUMMARIZATION_LLM_API_KEY: replace-if-required
